import { Inter } from "next/font/google";
import "./globals.css";
import ProviderWrapper from "./ProviderWrapper";
import Footer from "@/client/components/common/Footer";
import Navbar from "@/client/components/common/Navbar";
import ClientOnlyComponents from "@/client/components/ClientOnlyComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopping Next App",
  description: "Generated by Shopping next app",
  keywords: "",
  og: {
    title: "",
    description: "",
    image: "",
    url: "",
    site_name: "",
    locale: "",
    type: "",
  },
  canonical: "",
  robots: "",
  author: "",
  publisher: "",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*100th - commit u can do it Sathik */}
        {/*200th - commit [almost done, 😍u can do it Sathik🥰] */}
        {/*300th - commit [payment, encrypt decrypt , 
        centralized axios visitor, admin this all added few more sathik🥲😇🥰 */}

        <ProviderWrapper>
          <Navbar />
          {children}
          <Footer />
          <ClientOnlyComponents />
        </ProviderWrapper>
      </body>
    </html>
  );
}
